name: Update Daily Shop

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  update-shop:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Run shop generator script
        run: node generate_shop.js

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Backend/shop.json
          
  
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Автоматическое обновление магазина [skip ci]"
          git push
